#!/bin/bash
# Job name:
#SBATCH --job-name=jobTemp
#
#Project:
#SBATCH --account=uio
#
#Wall clock limit
#SBATCH --time=00:05:00
#
#Max memory usage:
#SBATCH --mem-per-cpu=700M

source /cluster/bin/jobsetup
module purge  # clear any inherited modules

## Copy input files to the work directory
cp -R /usit/abel/u1/dipeshpr/App/task35 $SCRATCH

# DO some work
cd $SCRATCH
cd task35
chmod +x jar1.jar
java -jar jar1.jar 'Test cases/src/Main/__init__.py' '1'
sleep 8
mv result.txt task35.txt
cp task35.txt /usit/abel/u1/dipeshpr/AppResult
