#!/bin/bash
# Job name:
#SBATCH --job-name=jobTemp
#
#Project:
#SBATCH --account=uio
#
#Wall clock limit
#SBATCH --time=00:03:00
#
#Max memory usage:
#SBATCH --mem-per-cpu=200M

source /cluster/bin/jobsetup
module purge  # clear any inherited modules
module load python2/2.7.9

## Copy input files to the work directory
cp -R /usit/abel/u1/dipeshpr/App/task74 $SCRATCH

# DO some work
cd $SCRATCH
cd task74
chmod +x jar1.jar
java -jar jar1.jar 'TestCases/src/Main/__init__.py' '9'
while [ ! -f "finished.txt" ]
do
  sleep 2
done
mv result.txt task74.txt
cp task74.txt /usit/abel/u1/dipeshpr/AppResult
