#!/bin/bash
# Job name:
#SBATCH --job-name=jobTemp
#
#Project:
#SBATCH --account=uio
#
#Wall clock limit
#SBATCH --time=00:05:00
#
#Max memory usage:
#SBATCH --mem-per-cpu=200M

source /cluster/bin/jobsetup
module purge  # clear any inherited modules
module load python2/2.7.9

## Copy input files to the work directory
cp -R /usit/abel/u1/dipeshpr/App/task54 $SCRATCH

# DO some work
cd $SCRATCH
cd task54
chmod +x jar1.jar
java -jar jar1.jar 'TestCases/src/Main/__init__.py' '3'
file=finished.txt
until [ ! -f "$file" ]
do
  sleep 2
done
mv result.txt task54.txt
cp task54.txt /usit/abel/u1/dipeshpr/AppResult
