#!/bin/bash
# Job name:
#SBATCH --job-name=jobTemp
#
#Project:
#SBATCH --account=uio
#
#Wall clock limit
#SBATCH --time=00:05:00
#
#Max memory usage:
#SBATCH --mem-per-cpu=200M

source /cluster/bin/jobsetup
module purge  # clear any inherited modules

## Copy input files to the work directory
cp -R /usit/abel/u1/dipeshpr/App/task5 $SCRATCH

# DO some work
cd $SCRATCH
cd task5
chmod +x jar1.jar
java -jar jar1.jar 2
sleep 8
mv result.txt task5.txt
cp task5.txt /usit/abel/u1/dipeshpr/AppResult
